"""Human-readable graph audit report (GRAPH_REPORT.md) — Graphify-parity output.

Graphify writes a GRAPH_REPORT.md beside graph.json; we render the equivalent
from our own Graph + Metrics so the EX04 deliverable exists whichever backend
produced the graph. Pure projection of committed facts — deterministic, no LLM.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from hw4.services.graph_metrics import Metrics
from hw4.services.graph_models import Graph


def render(graph: Graph, metrics: Metrics) -> str:
    node_types = Counter(node.type for node in graph.nodes.values())
    relations = Counter(edge.relation for edge in graph.edges)
    evidence = Counter(edge.evidence.value for edge in graph.edges)
    lines = [
        f"# GRAPH_REPORT — iteration {graph.iteration:02d}",
        "",
        f"Backend `{graph.backend}` · **{len(graph.nodes)} nodes** · "
        f"**{len(graph.edges)} edges** · {metrics.community_count} communities · "
        f"{len(metrics.isolated_components)} isolated components.",
        "",
        "## Nodes by type",
        *(f"- {kind}: {count}" for kind, count in node_types.most_common()),
        "",
        "## Edges by relation",
        *(f"- {relation}: {count}" for relation, count in relations.most_common()),
        "",
        "## Evidence classes (Part-C)",
        *(f"- {cls}: {count}" for cls, count in evidence.most_common()),
        "",
        "## Top dependency bottlenecks (rubric evidence, not a verdict)",
        "| rank | node | fan-in | fan-out | betweenness | mandatory-path |",
        "|---|---|---|---|---|---|",
        *(_bottleneck_row(b) for b in metrics.bottlenecks[:10]),
    ]
    largest = _largest_communities(metrics)
    if largest:
        lines += ["", "## Largest communities",
                  *(f"- community {cid}: {size} nodes" for cid, size in largest)]
    lines += ["", "_Generated by hw4 — deterministic projection of graph.json + metrics.json._"]
    return "\n".join(lines) + "\n"


def _bottleneck_row(bottleneck) -> str:
    return (f"| {bottleneck.rank} | `{bottleneck.node_id}` | {bottleneck.fan_in} | "
            f"{bottleneck.fan_out} | {bottleneck.betweenness:.3f} | "
            f"{bottleneck.mandatory_path_ratio:.3f} |")


def _largest_communities(metrics: Metrics) -> list[tuple[int, int]]:
    counts = Counter(metrics.community_of.values())
    return [(cid, size) for cid, size in counts.most_common(5) if size > 1]


def write(graph: Graph, metrics: Metrics, path: Path | str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(graph, metrics), encoding="utf-8")
    return path
