"""Obsidian vault skeleton, index, and ingestion log (FR-3.1/3.2, T173-T182).

Part-A taxonomy (Portfolio → Domains → Projects → Comparisons) with the
Part-B anatomy inside the project: raw/ vs wiki/ separation, index.md as
the ONLY default entry point, log.md as the append-only ingestion trail.

Ownership rule (T175): skeleton notes are written once and never
clobbered — humans may edit them. index.md is machine-owned (regenerated,
marked as such). log.md is append-only by construction.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from hw4.shared.config import Config

TAXONOMY = ("00_Portfolio", "10_Domains", "20_Projects", "30_Comparisons")
AUTO_MARK = "<!-- AUTO-GENERATED by hw4: do not hand-edit; regenerate instead -->"


def frontmatter(note_type: str, project: str, status: str = "active") -> str:
    return f"---\ntype: {note_type}\nstatus: {status}\nproject: {project}\n---\n"


class VaultBuilder:
    """Create and maintain the vault tree for one analysis project."""

    def __init__(self, config: Config, base_dir: Path | str = "."):
        self._project = str(config.get("vault.project"))
        self._domains = list(config.get("vault.domains"))
        self._vault = Path(base_dir) / config.path("vault")

    @property
    def project_dir(self) -> Path:
        return self._vault / "20_Projects" / self._project

    @property
    def wiki_dir(self) -> Path:
        return self.project_dir / "wiki"

    @property
    def raw_dir(self) -> Path:
        return self.project_dir / "raw"

    def build_skeleton(self) -> list[Path]:
        """Idempotent: creates what is missing, touches nothing that exists."""
        created = []
        for name in TAXONOMY:
            (self._vault / name).mkdir(parents=True, exist_ok=True)
        for sub in (self.raw_dir, self.wiki_dir):
            sub.mkdir(parents=True, exist_ok=True)
        created += [self._write_once(
            self._vault / "00_Portfolio" / "Portfolio.md",
            frontmatter("portfolio", self._project)
            + "# Portfolio — analysis projects routed by domain\n\n"
            + "".join(f"- [[{d}]]\n" for d in self._domains),
        )]
        for domain in self._domains:
            created.append(self._write_once(
                self._vault / "10_Domains" / f"{domain}.md",
                frontmatter("domain", self._project)
                + f"# {domain} — domain knowledge feeding [[{self._project}]]\n",
            ))
        created.append(self._write_once(
            self.project_dir / f"{self._project}.md",
            frontmatter("project", self._project)
            + f"# {self._project} — graph-guided reverse engineering of the target repo\n\n"
            + "Start at [[index]]. Raw inputs in raw/, distilled notes in wiki/.\n"
            + "Project governance: docs/PRD.md, docs/PLAN.md, docs/TODO.md (repo).\n",
        ))
        if not self.log_path.exists():
            self.log_path.write_text(
                frontmatter("log", self._project) + "# Ingestion log (append-only)\n",
                encoding="utf-8",
            )
            created.append(self.log_path)
        return [p for p in created if p is not None]

    @property
    def index_path(self) -> Path:
        return self.project_dir / "index.md"

    @property
    def hot_path(self) -> Path:
        return self.project_dir / "hot.md"

    @property
    def log_path(self) -> Path:
        return self.project_dir / "log.md"

    def write_hot(self, focus: dict) -> Path:
        """Machine-owned focused-context page for the hottest investigation area.

        hot.md is the minimal context to load *first* before reading source —
        the critical-area counterpart to the index's whole-project map (§5.1).
        """
        lines = [
            frontmatter("hot", self._project, status="generated").rstrip("\n"),
            AUTO_MARK,
            f"# hot — focused context for {focus['title']}",
            "",
            "> Load this first when investigating the critical area; it is the",
            "> minimal context a human or agent needs before opening source.",
            "",
            "## Why this is hot",
            focus["why"],
            "",
            "## Read first",
            *(f"- {item}" for item in focus["read_first"]),
            "",
            "## Evidence",
            *(f"- {row}" for row in focus["evidence"]),
        ]
        self.hot_path.parent.mkdir(parents=True, exist_ok=True)
        self.hot_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return self.hot_path

    def write_index(self, sections: dict[str, list[str]]) -> Path:
        """Regenerate the machine-owned navigation hub (stable order)."""
        lines = [
            frontmatter("index", self._project).rstrip("\n"),
            AUTO_MARK,
            f"# index — navigation hub for {self._project} (load this first)",
            "",
        ]
        for heading in sections:
            lines.append(f"## {heading}")
            lines.extend(f"- {entry}" for entry in sections[heading])
            lines.append("")
        self.index_path.parent.mkdir(parents=True, exist_ok=True)
        self.index_path.write_text("\n".join(lines), encoding="utf-8")
        return self.index_path

    def append_log(self, what: str, source: str, tool: str) -> None:
        """One traceability line per ingestion (Part-B)."""
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
        with self.log_path.open("a", encoding="utf-8") as fh:
            fh.write(f"- {stamp} · {what} · source: {source} · tool: {tool}\n")

    def _write_once(self, path: Path, content: str) -> Path | None:
        if path.exists():
            return None  # human may have edited it — never clobber
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path
